name: 🔍 PR Checks

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
jobs:
  pr-validation:
    if: github.actor != 'dependabot[bot]'
    uses: clouddrove/github-shared-workflows/.github/workflows/pr-checks.yml@master