name: Release

on:
  release:
    types: [published]

jobs:
  changelog:
    uses: clouddrove/github-shared-workflows/.github/workflows/release-changelog.yml@master
    with:
      branch: master
      tag_format: vX.Y.Z
      release_tag: ${{ github.ref_name }}
    secrets:
      GITHUB: ${{ secrets.GITHUB_TOKEN }}