name: tf-checks

permissions:
  contents: write

on:
  pull_request:
    paths:
      - '**/*.tf'
      - '*.tf'

jobs:
  iam-account:
    if: github.actor != 'dependabot[bot]'
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@master
    with:
      working_directory: ./examples/iam-account
      provider: aws
      enable_plan: true
      show_plan: false
    secrets:
      BUILD_ROLE: ${{ secrets.BUILD_ROLE }}

  iam-assumable-role:
    if: github.actor != 'dependabot[bot]'
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@master
    with:
      working_directory: ./examples/iam-assumable-role
      provider: aws
      enable_plan: true
      show_plan: false
    secrets:
      BUILD_ROLE: ${{ secrets.BUILD_ROLE }}

  iam-assumable-roles:
    if: github.actor != 'dependabot[bot]'
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@master
    with:
      working_directory: ./examples/iam-assumable-roles
      provider: aws
      enable_plan: true
      show_plan: false
    secrets:
      BUILD_ROLE: ${{ secrets.BUILD_ROLE }}

  iam-assumable-roles-with-saml:
    if: github.actor != 'dependabot[bot]'
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@master
    with:
      working_directory: ./examples/iam-assumable-roles-with-saml
      provider: aws
      enable_plan: true
      show_plan: false
    secrets:
      BUILD_ROLE: ${{ secrets.BUILD_ROLE }}

  iam-assumable-role-with-oidc:
    if: github.actor != 'dependabot[bot]'
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@master
    with:
      working_directory: ./examples/iam-assumable-role-with-oidc
      provider: aws
      enable_plan: true
      show_plan: false
    secrets:
      BUILD_ROLE: ${{ secrets.BUILD_ROLE }}

  iam-assumable-role-with-saml:
    if: github.actor != 'dependabot[bot]'
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@master
    with:
      working_directory: ./examples/iam-assumable-role-with-saml
      provider: aws
      enable_plan: true
      show_plan: false
    secrets:
      BUILD_ROLE: ${{ secrets.BUILD_ROLE }}

  iam-eks-role:
    if: github.actor != 'dependabot[bot]'
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@master
    with:
      working_directory: ./examples/iam-eks-role
      provider: aws
      enable_plan: true
      show_plan: false
    secrets:
      BUILD_ROLE: ${{ secrets.BUILD_ROLE }}

  iam-group-complete:
    if: github.actor != 'dependabot[bot]'
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@master
    with:
      working_directory: ./examples/iam-group-complete
      provider: aws
      enable_plan: true
      show_plan: false
    secrets:
      BUILD_ROLE: ${{ secrets.BUILD_ROLE }}

  iam-group-with-assumable-roles-policy:
    if: github.actor != 'dependabot[bot]'
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@master
    with:
      working_directory: ./examples/iam-group-with-assumable-roles-policy
      provider: aws
      enable_plan: true
      show_plan: false
    secrets:
      BUILD_ROLE: ${{ secrets.BUILD_ROLE }}

  iam-group-with-policies:
    if: github.actor != 'dependabot[bot]'
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@master
    with:
      working_directory: ./examples/iam-group-with-policies
      provider: aws
      enable_plan: true
      show_plan: false
    secrets:
      BUILD_ROLE: ${{ secrets.BUILD_ROLE }}

  iam-policy:
    if: github.actor != 'dependabot[bot]'
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@master
    with:
      working_directory: ./examples/iam-policy
      provider: aws
      enable_plan: true
      show_plan: false
    secrets:
      BUILD_ROLE: ${{ secrets.BUILD_ROLE }}

  iam-read-only-policy:
    if: github.actor != 'dependabot[bot]'
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@master
    with:
      working_directory: ./examples/iam-read-only-policy
      provider: aws
      enable_plan: true
      show_plan: false
    secrets:
      BUILD_ROLE: ${{ secrets.BUILD_ROLE }}

  iam-user:
    if: github.actor != 'dependabot[bot]'
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@master
    with:
      working_directory: ./examples/iam-user
      provider: aws
      enable_plan: true
      show_plan: false
    secrets:
      BUILD_ROLE: ${{ secrets.BUILD_ROLE }}